task:
  name: "Kernel deploy.."
  timeout_in: 120m
  container:
      image: nexgang/ubuntu:latest
      cpu: 8
      memory: 16G
      stateful: true
      greedy: true

  Build_script:
      - git clone --depth=1 -b oss-dyn https://github.com/Amritorock/kernel_realme_r5x r5x && cd r5x
      - bash build.sh 
