env:
    token: "ENCRYPTED[91aa86249a2b8217c4416fd0688d5f96bd0f1c00043f546a4c588cc41f1e1e9233082dbd36ac2f5624e3843ff1136e63]"
    chat_id: "ENCRYPTED[271123886e84714e0f103ef02e04c0e8f59d20e429fb1c0f118b20bf88b4a98f966b095e487c0ba21ceb314215d0b060]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 4
      memory: 16G

  Build_script:
     - echo "LC_ALL=en_US.UTF-8" | sudo tee -a /etc/environment
     - echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
     - echo "LANG=en_US.UTF-8" | sudo tee -a /etc/locale.conf
     - sudo locale-gen en_US.UTF-8
     - curl -fsSL "https://pkgbuild.com/~morganamilo/pacman-static/x86_64/bin/pacman-static" -o pacman-static && chmod +x pacman-static && mv pacman-static /usr/bin/
     - pacman-static -Syu --needed --noconfirm dpkg
     - wget http://archive.ubuntu.com/ubuntu/pool/main/n/ncurses/libtinfo5_6.0+20160213-1ubuntu1_amd64.deb -O libtinfo5.deb && dpkg-deb -R libtinfo5.deb libtinfo && cp libtinfo/lib/x86_64-linux-gnu/libtinfo.so.5.9 /usr/lib/libtinfo.so.5  
      - git clone --depth=1 -b rebase https://github.com/Prashant-1695/kernel_xiaomi_lavender-4.19 lv && mv build.sh lv/build.sh && cd lv
      - bash build.sh --proton
